
name: WorkFlow Test

# Controls when the workflow will run
on:
  workflow_dispatch:

concurrency:
  group: workflow-${{ github.workflow }}
  cancel-in-progress: true

env:
    LIBRARY_CACHE_PATH: project/Library


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile_project:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Check Xcode sdk
        run: /usr/bin/xcodebuild -showsdks

  
