
name: WorkFlow Test

# Controls when the workflow will run
on:
  workflow_dispatch:

concurrency:
  group: workflow-${{ github.workflow }}
  cancel-in-progress: true

env:
    LIBRARY_CACHE_PATH: project/Library


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          # UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64


      # Return License
      - name: Return license
        uses: game-ci/unity-return-license@v2
        if: always()

  
